### ISSUE TITLE
Watch CSS instead of Sass files?

### ISSUE THREAD

**Issue by evanmwillhite** [fourkitchens/emulsify-gulp#20]
Watching Sass sometimes causes a lag - should watch CSS instead?

**Comment by bradjones1** [comment]
Gulp also doesn't pick up new `scss` files, adding new Sass files requires a restart.

**Comment by rupl** [comment]
What lag do you mean? I found this issue after experiencing a race condition I found in the `gulp.watch` code. The `browserSync.reload` command fires [when the Sass file changes](https://github.com/fourkitchens/emulsify-gulp/blob/f6d5393189fa189de07b1e0b61f68004dadbb956/index.js#L110) instead of firing [at the end of the `cssCompile` function](https://github.com/fourkitchens/emulsify-gulp/blob/f6d5393189fa189de07b1e0b61f68004dadbb956/gulp-tasks/gulp-css.js#L50) which is where the `bs.reload` typically lives.

End effect is that the page refreshes before Sass can finish compiling. This happens at least 50% of refrehes in my experience. In fact I'm pretty sure the only thing that makes it work the other half of the time is the synchronous loading of fonts, also a bad bottleneck that imo should be async loaded out of the box.

**Comment by rupl** [comment]
As for the Sass not picking up new files, here are some related issues:

- https://github.com/sindresorhus/gulp-ruby-sass/issues/11
- https://github.com/shama/gaze/issues/66

I see in the gulp config that a large number of paths are prefixed with `./` by way of `themeDir` defaulting to that value. That might be the culprit.

**Comment by amazingrando** [comment]
#38 is merged and it triggers reload after the CSS is compiled. I'm going to close this issue.
