### ISSUE TITLE
Clean up/prune/organize tasks

### ISSUE THREAD

**Issue by infiniteluke** [fourkitchens/emulsify-gulp#4]
As per @evanmwillhite, many of these tasks are cool but probably won't be used. Create a PR remove any tasks you find unnecessary.

**Comment by rupl** [comment]
One thing I can recommend based on years of feedback from trainings is that there needs to be more documentation in the code. [Look at this other 4K gulpfile](https://github.com/fourkitchens/frontend-perf/blob/master/gulpfile.js) (I am the primary author) and the Emulsify gulpfile and I think you'll see how much friendlier it is for newbies, onboarding, etc. 

Yeah sure that other one is just one simple file instead of using modules and exports and blah blah, but all that code splitting makes it harder to understand not easier. It's doesn't run faster or make it more maintainable either.

As for removing things.. I think that removing PSI/WPT is a good call. Emulsify claims to be a PL+D8 glue layer, it doesn't need perf tests built in. Leave them in the other repo and keep that up to date instead, solves two problems.

**Comment by amazingrando** [comment]
I'm going to close this issue since there hasn't been much movement on it in months. If we'd like to remove tasks, such as PSI/WPT, let's create a specific issue for it.
